version: '3.3'
services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.5.0
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
      - ./policies:/opt/tyk-gateway/policies
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
  animalservice:
    build:
      context: ./goservice
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=18080
      - SERVICE_NAME=animalservice
    ports:
      - 18080:18080
    networks:
      - tyk
  vehicleservice:
    build:
      context: ./goservice
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=18081
      - SERVICE_NAME=vehicleservice
    ports:
      - 18081:18081
    networks:
      - tyk
  tyk-redis:
    image: redis:6.2.20-alpine
    networks:
      - tyk
    ports:
      - 6379:6379

networks:
  tyk:
